name: Build
on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP with logs
        uses: shivammathur/setup-php@verbose
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl
          ini-values: phar.readonly=Off

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate runtime
        run: |
          chmod +x ./bin/create
          ./bin/create
        shell: bash

      # Get the release ID using GitHub REST API
      - name: Get Release ID
        id: get_release
        run: |
          release_id=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${GITHUB_REF_NAME}" | jq -r '.id')
          echo "release_id=$release_id" >> $GITHUB_OUTPUT

      - name: Test GITHUB_OUTPUT
        run: cat "${GITHUB_OUTPUT}"

      # Upload the generated file as an asset to the existing release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release.outputs.release_id }}/assets?name=sslgen.phar
          asset_path: ./sslgen.phar
          asset_name: sslgen.phar
          asset_content_type: text/plain