name: Build
on:
  push:
    tags:
      - 'v*'

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP with logs
        uses: shivammathur/setup-php@verbose
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Adjust phar extension settings
        run: sudo echo "phar.readonly = Off" >> /etc/php/8.3/cli/conf.d/20-phar.ini

      - name: Generate runtime
        run: |
          chmod +x ./bin/create
          ./bin/create
        shell: bash