name: Build
on:
  push:
    tags:
      - 'v*'

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with logs
        uses: shivammathur/setup-php@verbose
        with:
          php-version: '8.3'
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Generate runtime
        run: |
          chmod +x ./bin/create
          ./bin/create
        shell: bash